-- down.sql: Reverse initial migration

DROP TABLE IF EXISTS webhook_configs CASCADE;
DROP TABLE IF EXISTS alert_events CASCADE;
DROP TABLE IF EXISTS alert_rules CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS lenses CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS detected_issues CASCADE;
DROP TABLE IF EXISTS markers CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS api_tokens CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS users CASCADE;
