apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benchify.fullname" . }}-secret
  labels:
    {{- include "benchify.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_url: {{ include "benchify.databaseUrl" . | quote }}
  jwt_secret: {{ .Values.server.jwtSecret | quote }}
  {{- if .Values.server.jira.enabled }}
  jira_base_url: {{ .Values.server.jira.baseUrl | quote }}
  jira_email: {{ .Values.server.jira.email | quote }}
  jira_api_token: {{ .Values.server.jira.apiToken | quote }}
  {{- end }}
  {{- if .Values.server.smtp.host }}
  smtp_username: {{ .Values.server.smtp.username | quote }}
  smtp_password: {{ .Values.server.smtp.password | quote }}
  {{- end }}
  {{- if .Values.server.slack.webhookUrl }}
  slack_webhook_url: {{ .Values.server.slack.webhookUrl | quote }}
  {{- end }}
